[package]
name = "cookbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
clap = "4.4.6"
flate2 = "1.0.27"
rand = "0.8.5"
rand_distr = "0.4.3"
tar = "0.4.40"
